// @ts-check

// The sidebar is autogenerated from the docs/ folder structure plus each page's
// sidebar_position front matter and _category_.json files. See CONTENT-MODEL.md.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
